const sampleListings = [
  {
    title: "Cozy Beachfront Cottage",
    description: "Escape to this charming beachfront cottage for a relaxing getaway.",
    image: "https://images.unsplash.com/photo-1525741081-9d7c0d7c0c5a",
    price: 1500,
    location: "Malibu",
    country: "United States",
  },
  {
    title: "Modern Loft in Downtown",
    description: "Stay in the heart of the city in this stylish modern loft apartment.",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
    price: 1200,
    location: "New York City",
    country: "United States",
  },
  {
    title: "Mountain Retreat",
    description: "Enjoy peaceful mountain views from this beautiful countryside retreat.",
    image: "https://images.unsplash.com/photo-1510798831971-661eb04b3739",
    price: 1800,
    location: "Aspen",
    country: "United States",
  },
  {
    title: "Luxury Villa with Pool",
    description: "Relax in this luxurious villa featuring a private swimming pool.",
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811",
    price: 3500,
    location: "Miami",
    country: "United States",
  },
  {
    title: "Cozy Cabin in the Woods",
    description: "A peaceful wooden cabin surrounded by beautiful forests and nature.",
    image: "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8",
    price: 1100,
    location: "Lake Tahoe",
    country: "United States",
  },
  {
    title: "Seaside Apartment",
    description: "Wake up to stunning ocean views in this comfortable seaside apartment.",
    image: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2",
    price: 2200,
    location: "Santa Monica",
    country: "United States",
  },
  {
    title: "Elegant City Apartment",
    description: "A modern apartment located close to restaurants, shops, and attractions.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    price: 1400,
    location: "Chicago",
    country: "United States",
  },
  {
    title: "Rustic Farmhouse",
    description: "Experience countryside living in this beautiful rustic farmhouse.",
    image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef",
    price: 1700,
    location: "Nashville",
    country: "United States",
  },
  {
    title: "Ocean View Villa",
    description: "A stunning villa offering panoramic views of the ocean and coastline.",
    image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d",
    price: 4200,
    location: "Honolulu",
    country: "United States",
  },
  {
    title: "Minimalist Studio",
    description: "A clean and modern studio perfect for solo travelers and couples.",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
    price: 900,
    location: "Boston",
    country: "United States",
  },
  {
    title: "Luxury Downtown Condo",
    description: "Enjoy premium amenities and city views from this luxury condominium.",
    image: "https://images.unsplash.com/photo-1600607688969-a5bfcd646154",
    price: 2500,
    location: "Los Angeles",
    country: "United States",
  },
  {
    title: "Hidden Forest Cottage",
    description: "A quiet cottage hidden among tall trees and beautiful forest trails.",
    image: "https://images.unsplash.com/photo-1510798831971-661eb04b3739",
    price: 1300,
    location: "Portland",
    country: "United States",
  },
  {
    title: "Riverside Retreat",
    description: "Spend your vacation beside a peaceful river surrounded by nature.",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
    price: 1600,
    location: "Bend",
    country: "United States",
  },
  {
    title: "Modern Beach House",
    description: "A stylish beach house with spacious rooms and incredible ocean views.",
    image: "https://images.unsplash.com/photo-1494526585095-c41746248156",
    price: 3000,
    location: "San Diego",
    country: "United States",
  },
  {
    title: "Historic Townhouse",
    description: "Stay in a charming historic townhouse located in the city center.",
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994",
    price: 1900,
    location: "Boston",
    country: "United States",
  },
  {
    title: "Luxury Mountain Lodge",
    description: "Enjoy breathtaking mountain scenery from this luxurious mountain lodge.",
    image: "https://images.unsplash.com/photo-1542718610-a1d656d1884c",
    price: 2800,
    location: "Denver",
    country: "United States",
  },
  {
    title: "Coastal Escape",
    description: "Relax near the beach in this peaceful and comfortable coastal home.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
    price: 2100,
    location: "Charleston",
    country: "United States",
  },
  {
    title: "Urban Penthouse",
    description: "Experience luxury living in this spacious downtown penthouse.",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c",
    price: 5000,
    location: "New York City",
    country: "United States",
  },
  {
    title: "Lakeside Cabin",
    description: "A cozy cabin with direct access to a beautiful peaceful lake.",
    image: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e",
    price: 1450,
    location: "Lake Tahoe",
    country: "United States",
  },
  {
    title: "Charming Garden Home",
    description: "Stay in a beautiful home surrounded by colorful gardens.",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6",
    price: 1550,
    location: "San Francisco",
    country: "United States",
  },
  {
    title: "Desert Villa",
    description: "A beautiful desert retreat with modern architecture and open spaces.",
    image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d",
    price: 2300,
    location: "Scottsdale",
    country: "United States",
  },
  {
    title: "Snowy Mountain Cabin",
    description: "Perfect winter getaway surrounded by snowy mountain landscapes.",
    image: "https://images.unsplash.com/photo-1480074568708-e7b720bb3f09",
    price: 2000,
    location: "Jackson Hole",
    country: "United States",
  },
  {
    title: "Luxury Lakeside Villa",
    description: "A spacious villa offering beautiful lake views and premium amenities.",
    image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d",
    price: 3800,
    location: "Orlando",
    country: "United States",
  },
  {
    title: "Downtown Studio",
    description: "Affordable studio apartment located close to the city's main attractions.",
    image: "https://images.unsplash.com/photo-1524758631624-e2822e304c36",
    price: 850,
    location: "Seattle",
    country: "United States",
  },
  {
    title: "Private Island House",
    description: "Enjoy ultimate privacy in this stunning island vacation home.",
    image: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2",
    price: 6000,
    location: "Key West",
    country: "United States",
  },
  {
    title: "Countryside Cottage",
    description: "A peaceful countryside cottage perfect for a relaxing weekend.",
    image: "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8",
    price: 1250,
    location: "Austin",
    country: "United States",
  },
  {
    title: "Modern Glass House",
    description: "A stunning modern home featuring large windows and natural light.",
    image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d",
    price: 3200,
    location: "Palm Springs",
    country: "United States",
  },
  {
    title: "Beachside Bungalow",
    description: "A cozy bungalow just steps away from the sandy beach.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    price: 1800,
    location: "Miami Beach",
    country: "United States",
  },
  {
    title: "Historic Villa",
    description: "Stay in a beautifully preserved villa filled with classic architecture.",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6",
    price: 2400,
    location: "Savannah",
    country: "United States",
  },
  {
    title: "Forest View Apartment",
    description: "A peaceful apartment overlooking a lush green forest.",
    image: "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8",
    price: 1350,
    location: "Asheville",
    country: "United States",
  },
  {
    title: "Luxury Ski Chalet",
    description: "Enjoy skiing and mountain adventures from this luxury chalet.",
    image: "https://images.unsplash.com/photo-1542718610-a1d656d1884c",
    price: 3600,
    location: "Vail",
    country: "United States",
  },
  {
    title: "Tropical Paradise Villa",
    description: "A tropical villa surrounded by palm trees and beautiful beaches.",
    image: "https://images.unsplash.com/photo-1500534623283-312aade485b7",
    price: 4100,
    location: "Maui",
    country: "United States",
  },
  {
    title: "City View Apartment",
    description: "Modern apartment with stunning views of the city skyline.",
    image: "https://images.unsplash.com/photo-1515263487990-61b07816b324",
    price: 1750,
    location: "Atlanta",
    country: "United States",
  },
  {
    title: "Peaceful River House",
    description: "Relax beside the river in this spacious and peaceful vacation home.",
    image: "https://images.unsplash.com/photo-1500534623283-312aade485b7",
    price: 1650,
    location: "Boise",
    country: "United States",
  },
  {
    title: "Luxury Country Estate",
    description: "A large private estate surrounded by beautiful countryside.",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6",
    price: 4500,
    location: "Dallas",
    country: "United States",
  },
  {
    title: "Cozy Downtown Home",
    description: "Comfortable home located within walking distance of downtown attractions.",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be",
    price: 1450,
    location: "Philadelphia",
    country: "United States",
  },
  {
    title: "Sunset Beach House",
    description: "Watch beautiful sunsets from this comfortable beach house.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    price: 2700,
    location: "Santa Barbara",
    country: "United States",
  },
  {
    title: "Modern Mountain Home",
    description: "A contemporary home with breathtaking mountain views.",
    image: "https://images.unsplash.com/photo-1510798831971-661eb04b3739",
    price: 2900,
    location: "Salt Lake City",
    country: "United States",
  },
  {
    title: "Chic Urban Loft",
    description: "Stylish loft apartment in one of the city's most vibrant neighborhoods.",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
    price: 1550,
    location: "Brooklyn",
    country: "United States",
  },
  {
    title: "Lakefront Mansion",
    description: "Luxury mansion with private lake access and spacious living areas.",
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811",
    price: 5500,
    location: "Lake Placid",
    country: "United States",
  },
  {
    title: "Rustic Mountain Cabin",
    description: "Traditional wooden cabin perfect for nature lovers.",
    image: "https://images.unsplash.com/photo-1542718610-a1d656d1884c",
    price: 1350,
    location: "Montana",
    country: "United States",
  },
  {
    title: "Elegant Beach Villa",
    description: "Elegant vacation villa with a private pool near the beach.",
    image: "https://images.unsplash.com/photo-1600607688969-a5bfcd646154",
    price: 3300,
    location: "Naples",
    country: "United States",
  },
  {
    title: "Cozy City Retreat",
    description: "A comfortable retreat in the middle of a busy city.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    price: 1150,
    location: "Washington DC",
    country: "United States",
  },
  {
    title: "Forest Luxury Lodge",
    description: "Luxury lodge surrounded by tall trees and peaceful walking trails.",
    image: "https://images.unsplash.com/photo-1510798831971-661eb04b3739",
    price: 2600,
    location: "Boulder",
    country: "United States",
  },
  {
    title: "Sunny Coastal Home",
    description: "Bright and comfortable home located near the beautiful coastline.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
    price: 1950,
    location: "Tampa",
    country: "United States",
  },
  {
    title: "Luxury City Penthouse",
    description: "Premium penthouse with panoramic skyline views and modern interiors.",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c",
    price: 4800,
    location: "Los Angeles",
    country: "United States",
  },
  {
    title: "Countryside Manor",
    description: "Spacious manor house surrounded by beautiful green landscapes.",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6",
    price: 3700,
    location: "Charlottesville",
    country: "United States",
  },
  {
    title: "Modern Lakeside Home",
    description: "Modern home with large windows overlooking a peaceful lake.",
    image: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e",
    price: 2450,
    location: "Madison",
    country: "United States",
  },
  {
    title: "Tropical Beach Cottage",
    description: "Small and cozy cottage perfect for a tropical vacation.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    price: 1750,
    location: "Key Largo",
    country: "United States",
  },
  {
    title: "Downtown Luxury Suite",
    description: "A luxurious suite located in the center of the city.",
    image: "https://images.unsplash.com/photo-1515263487990-61b07816b324",
    price: 2100,
    location: "Houston",
    country: "United States",
  },
  {
    title: "Mountain View Cottage",
    description: "Charming cottage offering incredible views of the surrounding mountains.",
    image: "https://images.unsplash.com/photo-1480074568708-e7b720bb3f09",
    price: 1500,
    location: "Flagstaff",
    country: "United States",
  },
  {
    title: "Private Pool Retreat",
    description: "Relax in this private home featuring a beautiful swimming pool.",
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811",
    price: 2800,
    location: "Scottsdale",
    country: "United States",
  },
  {
    title: "Stylish Studio Apartment",
    description: "Compact and stylish apartment perfect for a short city stay.",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
    price: 950,
    location: "Denver",
    country: "United States",
  },
  {
    title: "Beachfront Luxury Condo",
    description: "Modern condominium with direct access to a beautiful sandy beach.",
    image: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2",
    price: 2900,
    location: "Fort Lauderdale",
    country: "United States",
  },
  {
    title: "Woodland Retreat",
    description: "A peaceful home surrounded by woods and fresh mountain air.",
    image: "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8",
    price: 1200,
    location: "Olympic Peninsula",
    country: "United States",
  },
  {
    title: "Luxury Oceanfront Home",
    description: "Spacious luxury home overlooking the endless blue ocean.",
    image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d",
    price: 3900,
    location: "Newport Beach",
    country: "United States",
  },
  {
    title: "Historic Downtown Loft",
    description: "Beautiful loft combining historic architecture with modern comforts.",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
    price: 1600,
    location: "New Orleans",
    country: "United States",
  },
  {
    title: "Cozy Winter Chalet",
    description: "Warm and inviting chalet perfect for a winter holiday.",
    image: "https://images.unsplash.com/photo-1542718610-a1d656d1884c",
    price: 2300,
    location: "Breckenridge",
    country: "United States",
  },
  {
    title: "Modern Desert House",
    description: "Contemporary desert home with stunning sunset views.",
    image: "https://images.unsplash.com/photo-1600607688969-a5bfcd646154",
    price: 2600,
    location: "Joshua Tree",
    country: "United States",
  },
  {
    title: "Garden Villa",
    description: "Beautiful villa surrounded by colorful gardens and greenery.",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6",
    price: 2250,
    location: "San Jose",
    country: "United States",
  },
  {
    title: "Ocean Breeze Apartment",
    description: "Bright apartment with fresh ocean breezes and coastal views.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
    price: 1850,
    location: "Virginia Beach",
    country: "United States",
  },
  {
    title: "Luxury Forest Villa",
    description: "Private luxury villa surrounded by peaceful forests.",
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811",
    price: 3400,
    location: "Lake Arrowhead",
    country: "United States",
  },
  {
    title: "Riverside Cabin",
    description: "Cozy cabin located directly beside a calm flowing river.",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
    price: 1250,
    location: "Missoula",
    country: "United States",
  },
  {
    title: "Luxury Downtown Apartment",
    description: "Modern apartment close to restaurants, shopping, and nightlife.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    price: 1800,
    location: "San Francisco",
    country: "United States",
  },
  {
    title: "Secluded Beach Cottage",
    description: "Enjoy complete peace and privacy in this charming beach cottage.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    price: 2050,
    location: "Outer Banks",
    country: "United States",
  },
  {
    title: "Mountain Luxury Estate",
    description: "Large luxury estate with incredible panoramic mountain views.",
    image: "https://images.unsplash.com/photo-1510798831971-661eb04b3739",
    price: 5200,
    location: "Park City",
    country: "United States",
  },
  {
    title: "Urban Garden Apartment",
    description: "Modern city apartment featuring a private garden space.",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6",
    price: 1650,
    location: "Washington DC",
    country: "United States",
  },
  {
    title: "Lakeside Luxury Cabin",
    description: "Beautiful cabin with private lake views and outdoor seating.",
    image: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e",
    price: 2150,
    location: "Lake George",
    country: "United States",
  },
  {
    title: "Sunny Mountain Retreat",
    description: "Bright mountain retreat perfect for families and groups.",
    image: "https://images.unsplash.com/photo-1480074568708-e7b720bb3f09",
    price: 1900,
    location: "Santa Fe",
    country: "United States",
  },
  {
    title: "Elegant Coastal Villa",
    description: "Elegant villa located just minutes from the ocean.",
    image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d",
    price: 3100,
    location: "Monterey",
    country: "United States",
  },
  {
    title: "Cozy City Loft",
    description: "Stylish loft with an open floor plan in the city center.",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
    price: 1350,
    location: "Detroit",
    country: "United States",
  },
  {
    title: "Private Mountain Cabin",
    description: "Private cabin surrounded by beautiful mountains and trees.",
    image: "https://images.unsplash.com/photo-1542718610-a1d656d1884c",
    price: 1550,
    location: "Big Bear",
    country: "United States",
  },
  {
    title: "Luxury Pool House",
    description: "Modern vacation house featuring a large private pool.",
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811",
    price: 3600,
    location: "Las Vegas",
    country: "United States",
  },
  {
    title: "Charming Village Home",
    description: "Peaceful home located in a quiet and charming village.",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be",
    price: 1150,
    location: "Burlington",
    country: "United States",
  },
  {
    title: "Modern Waterfront Villa",
    description: "Contemporary villa overlooking beautiful waterfront scenery.",
    image: "https://images.unsplash.com/photo-1600607688969-a5bfcd646154",
    price: 4300,
    location: "Seattle",
    country: "United States",
  },
  {
    title: "Coastal Family Home",
    description: "Spacious family-friendly home located close to the beach.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
    price: 2200,
    location: "Jacksonville",
    country: "United States",
  },
  {
    title: "Forest Edge Cottage",
    description: "Charming cottage sitting at the edge of a peaceful forest.",
    image: "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8",
    price: 1400,
    location: "Eugene",
    country: "United States",
  },
  {
    title: "Luxury Skyline Condo",
    description: "High-end condo with amazing views of the city skyline.",
    image: "https://images.unsplash.com/photo-1515263487990-61b07816b324",
    price: 2700,
    location: "Charlotte",
    country: "United States",
  },
  {
    title: "Peaceful Lakeside Cottage",
    description: "Relax by the water in this peaceful and cozy cottage.",
    image: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e",
    price: 1350,
    location: "Traverse City",
    country: "United States",
  },
  {
    title: "Desert Sunset Villa",
    description: "Enjoy stunning desert sunsets from this modern private villa.",
    image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d",
    price: 2800,
    location: "Sedona",
    country: "United States",
  },
  {
    title: "Luxury Beach Mansion",
    description: "Large beachfront mansion with luxurious rooms and amenities.",
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811",
    price: 6500,
    location: "Malibu",
    country: "United States",
  },
  {
    title: "Downtown Family Apartment",
    description: "Spacious apartment located near parks, restaurants, and shops.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    price: 1700,
    location: "Minneapolis",
    country: "United States",
  },
  {
    title: "Rustic Countryside Lodge",
    description: "Traditional lodge surrounded by peaceful countryside landscapes.",
    image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef",
    price: 1600,
    location: "Lancaster",
    country: "United States",
  },
  {
    title: "Oceanfront Studio",
    description: "Small modern studio offering beautiful oceanfront views.",
    image: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2",
    price: 1250,
    location: "Galveston",
    country: "United States",
  },
  {
    title: "Mountain Family Lodge",
    description: "Large lodge perfect for families enjoying a mountain vacation.",
    image: "https://images.unsplash.com/photo-1542718610-a1d656d1884c",
    price: 2400,
    location: "Gatlinburg",
    country: "United States",
  },
  {
    title: "Modern City Residence",
    description: "Beautiful modern residence located in a vibrant neighborhood.",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6",
    price: 2000,
    location: "Phoenix",
    country: "United States",
  },
  {
    title: "Private Garden Cottage",
    description: "Cozy cottage with a peaceful private garden.",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be",
    price: 1300,
    location: "Portland",
    country: "United States",
  },
  {
    title: "Luxury Ocean Retreat",
    description: "Premium retreat with spectacular ocean views and modern interiors.",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c",
    price: 4000,
    location: "Laguna Beach",
    country: "United States",
  },
  {
    title: "Cozy Hillside Home",
    description: "Beautiful hillside home overlooking the surrounding landscape.",
    image: "https://images.unsplash.com/photo-1480074568708-e7b720bb3f09",
    price: 1750,
    location: "Los Angeles",
    country: "United States",
  },
  {
    title: "Secluded Forest Villa",
    description: "Private villa surrounded by peaceful forest and nature.",
    image: "https://images.unsplash.com/photo-1510798831971-661eb04b3739",
    price: 2900,
    location: "Bend",
    country: "United States",
  },
  {
    title: "Bright Beach Apartment",
    description: "Bright modern apartment just a short walk from the beach.",
    image: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2",
    price: 1900,
    location: "Clearwater",
    country: "United States",
  },
  {
    title: "Luxury Country Villa",
    description: "Spacious villa surrounded by peaceful countryside and gardens.",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6",
    price: 3300,
    location: "Lexington",
    country: "United States",
  },
  {
    title: "Downtown Business Loft",
    description: "Modern loft perfect for business travelers and city explorers.",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
    price: 1500,
    location: "Dallas",
    country: "United States",
  },
  {
    title: "Snowy Forest Lodge",
    description: "Warm lodge surrounded by snowy forests and winter scenery.",
    image: "https://images.unsplash.com/photo-1542718610-a1d656d1884c",
    price: 2100,
    location: "Anchorage",
    country: "United States",
  },
  {
    title: "Island Vacation Home",
    description: "Beautiful vacation home surrounded by tropical island scenery.",
    image: "https://images.unsplash.com/photo-1500534623283-312aade485b7",
    price: 3200,
    location: "Honolulu",
    country: "United States",
  },
  {
    title: "Modern Family Villa",
    description: "Spacious modern villa ideal for family vacations and gatherings.",
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811",
    price: 3000,
    location: "Orlando",
    country: "United States",
  },
  {
    title: "Peaceful Countryside Home",
    description: "Enjoy a quiet vacation away from the noise of the city.",
    image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef",
    price: 1450,
    location: "Iowa City",
    country: "United States",
  },
  {
    title: "Luxury City Residence",
    description: "Elegant residence with modern furniture and premium amenities.",
    image: "https://images.unsplash.com/photo-1600607688969-a5bfcd646154",
    price: 2600,
    location: "Austin",
    country: "United States",
  },
  {
    title: "Coastal Sunset Cottage",
    description: "Watch beautiful sunsets from this charming coastal cottage.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    price: 1750,
    location: "Destin",
    country: "United States",
  },
  {
    title: "Mountain Lake House",
    description: "A beautiful lake house surrounded by breathtaking mountains.",
    image: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e",
    price: 2800,
    location: "Lake Tahoe",
    country: "United States",
  },
  {
    title: "Elegant Urban Apartment",
    description: "Stylish apartment located close to the city's major attractions.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    price: 1550,
    location: "New York City",
    country: "United States",
  },
  {
    title: "Private Beach Bungalow",
    description: "Relax in this private bungalow just steps away from the ocean.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
    price: 2400,
    location: "San Diego",
    country: "United States",
  },
  {
    title: "Forest Mountain Cabin",
    description: "A cozy cabin combining forest privacy with mountain views.",
    image: "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8",
    price: 1550,
    location: "Asheville",
    country: "United States",
  },
  {
    title: "Luxury Waterfront Estate",
    description: "Beautiful waterfront estate with spacious rooms and private grounds.",
    image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d",
    price: 4700,
    location: "Miami",
    country: "United States",
  },
  {
    title: "Charming City Townhouse",
    description: "Comfortable townhouse in a quiet neighborhood close to downtown.",
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994",
    price: 1800,
    location: "Philadelphia",
    country: "United States",
  },
  {
    title: "Modern Pool Villa",
    description: "Contemporary villa featuring a private pool and spacious patio.",
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811",
    price: 3500,
    location: "Palm Springs",
    country: "United States",
  },
  {
    title: "Quiet Mountain Cottage",
    description: "A peaceful cottage perfect for escaping the busy city lifestyle.",
    image: "https://images.unsplash.com/photo-1480074568708-e7b720bb3f09",
    price: 1250,
    location: "Boone",
    country: "United States",
  },
  {
    title: "Beachside Family Villa",
    description: "Spacious villa close to the beach with plenty of room for families.",
    image: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2",
    price: 2600,
    location: "Corpus Christi",
    country: "United States",
  },
  {
    title: "Luxury Forest Estate",
    description: "Exclusive estate offering privacy, luxury, and beautiful forest views.",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6",
    price: 4200,
    location: "Seattle",
    country: "United States",
  },
  {
    title: "Cozy Riverside Cottage",
    description: "Charming cottage with peaceful river views and outdoor seating.",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
    price: 1350,
    location: "Portland",
    country: "United States",
  },
  {
    title: "Downtown Luxury Loft",
    description: "Spacious luxury loft in the center of the city's entertainment district.",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
    price: 2300,
    location: "Chicago",
    country: "United States",
  },
  {
    title: "Tropical Garden Villa",
    description: "Beautiful villa surrounded by tropical plants and lush gardens.",
    image: "https://images.unsplash.com/photo-1500534623283-312aade485b7",
    price: 3100,
    location: "Maui",
    country: "United States",
  },
  {
    title: "Modern Lake Retreat",
    description: "Contemporary retreat with peaceful lake views and modern interiors.",
    image: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e",
    price: 2250,
    location: "Madison",
    country: "United States",
  },
  {
    title: "Historic Coastal House",
    description: "Beautiful historic house located near the coast and local attractions.",
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994",
    price: 1950,
    location: "Savannah",
    country: "United States",
  },
  {
    title: "Luxury Hillside Villa",
    description: "Stunning hillside villa with panoramic views and luxury amenities.",
    image: "https://images.unsplash.com/photo-1600607688969-a5bfcd646154",
    price: 3800,
    location: "Los Angeles",
    country: "United States",
  },
  {
    title: "Cozy Snow Cabin",
    description: "Warm wooden cabin perfect for enjoying snowy winter landscapes.",
    image: "https://images.unsplash.com/photo-1542718610-a1d656d1884c",
    price: 1800,
    location: "Vermont",
    country: "United States",
  },
  {
    title: "Ocean Breeze Villa",
    description: "Beautiful villa with fresh ocean air and stunning coastal views.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
    price: 2900,
    location: "Santa Barbara",
    country: "United States",
  },
  {
    title: "Modern Downtown Home",
    description: "Comfortable modern home close to shopping, dining, and entertainment.",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be",
    price: 1600,
    location: "Austin",
    country: "United States",
  },
  {
    title: "Private Lakeside Villa",
    description: "Luxury villa with private lake access and beautiful outdoor spaces.",
    image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d",
    price: 3600,
    location: "Lake Tahoe",
    country: "United States",
  },
  {
    title: "Quiet Forest Retreat",
    description: "A peaceful retreat surrounded by nature and beautiful forest trails.",
    image: "https://images.unsplash.com/photo-1510798831971-661eb04b3739",
    price: 1450,
    location: "Bend",
    country: "United States",
  },
  {
    title: "Luxury Beachfront Estate",
    description: "Exclusive beachfront estate offering privacy and spectacular ocean views.",
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811",
    price: 5800,
    location: "Malibu",
    country: "United States",
  },
  {
    title: "Chic Downtown Studio",
    description: "Affordable and stylish studio in a convenient downtown location.",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
    price: 1000,
    location: "Boston",
    country: "United States",
  },
  {
    title: "Mountain View Estate",
    description: "Large estate with breathtaking views of the surrounding mountains.",
    image: "https://images.unsplash.com/photo-1510798831971-661eb04b3739",
    price: 4300,
    location: "Aspen",
    country: "United States",
  },
  {
    title: "Coastal Luxury Apartment",
    description: "Modern luxury apartment with direct access to the coastline.",
    image: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2",
    price: 2500,
    location: "Santa Monica",
    country: "United States",
  },
  {
    title: "Rustic Lake Cabin",
    description: "Traditional cabin offering beautiful lake views and peaceful surroundings.",
    image: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e",
    price: 1300,
    location: "Lake Placid",
    country: "United States",
  },
  {
    title: "Elegant Garden Residence",
    description: "Elegant residence surrounded by beautiful gardens and greenery.",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6",
    price: 2200,
    location: "San Francisco",
    country: "United States",
  },
  {
    title: "Sunset Mountain Lodge",
    description: "Enjoy unforgettable sunsets from this peaceful mountain lodge.",
    image: "https://images.unsplash.com/photo-1542718610-a1d656d1884c",
    price: 2450,
    location: "Jackson Hole",
    country: "United States",
  },
  {
    title: "Modern Ocean House",
    description: "Beautiful contemporary home with large windows facing the ocean.",
    image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d",
    price: 3400,
    location: "Newport Beach",
    country: "United States",
  },
  {
    title: "Cozy Urban Apartment",
    description: "Comfortable apartment in a lively neighborhood close to downtown.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    price: 1250,
    location: "Atlanta",
    country: "United States",
  },
  {
    title: "Private Desert Retreat",
    description: "Peaceful desert home offering beautiful landscapes and privacy.",
    image: "https://images.unsplash.com/photo-1600607688969-a5bfcd646154",
    price: 2000,
    location: "Sedona",
    country: "United States",
  },
  {
    title: "Luxury City Penthouse",
    description: "Premium penthouse featuring modern interiors and stunning skyline views.",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c",
    price: 5200,
    location: "New York City",
    country: "United States",
  },
  {
    title: "Peaceful Beach Cottage",
    description: "A charming cottage perfect for relaxing beside the ocean.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    price: 1650,
    location: "Outer Banks",
    country: "United States",
  },
  {
    title: "Luxury Mountain Retreat",
    description: "High-end mountain retreat with breathtaking views and premium amenities.",
    image: "https://images.unsplash.com/photo-1480074568708-e7b720bb3f09",
    price: 3200,
    location: "Vail",
    country: "United States",
  },
  {
    title: "Modern Riverside Home",
    description: "Modern home overlooking a peaceful river and surrounding greenery.",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
    price: 2300,
    location: "Bend",
    country: "United States",
  },
  {
    title: "Tropical Luxury Cottage",
    description: "Relax in this tropical cottage surrounded by palm trees and beaches.",
    image: "https://images.unsplash.com/photo-1500534623283-312aade485b7",
    price: 2700,
    location: "Key West",
    country: "United States",
  },
  {
    title: "Historic City Apartment",
    description: "Charming apartment combining historic character with modern comfort.",
    image: "https://images.unsplash.com/photo-1515263487990-61b07816b324",
    price: 1450,
    location: "New Orleans",
    country: "United States",
  },
  {
    title: "Private Pool Mansion",
    description: "Large luxury mansion with a private pool and spacious outdoor area.",
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811",
    price: 6000,
    location: "Miami",
    country: "United States",
  },
  {
    title: "Cozy Hillside Cottage",
    description: "Small cottage offering peaceful hillside views and fresh mountain air.",
    image: "https://images.unsplash.com/photo-1480074568708-e7b720bb3f09",
    price: 1200,
    location: "Asheville",
    country: "United States",
  },
  {
    title: "Luxury Coastal Estate",
    description: "Large coastal estate with elegant interiors and ocean views.",
    image: "https://images.unsplash.com/photo-1600607688969-a5bfcd646154",
    price: 4400,
    location: "Monterey",
    country: "United States",
  },
  {
    title: "Modern Family Home",
    description: "Spacious modern home perfect for families and longer stays.",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6",
    price: 2100,
    location: "Dallas",
    country: "United States",
  },
  {
    title: "Secluded Mountain Villa",
    description: "Private villa surrounded by mountains and peaceful natural scenery.",
    image: "https://images.unsplash.com/photo-1510798831971-661eb04b3739",
    price: 3500,
    location: "Montana",
    country: "United States",
  },
  {
    title: "Bright Coastal Studio",
    description: "Bright studio apartment located only minutes from the beach.",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
    price: 1100,
    location: "Tampa",
    country: "United States",
  },
  {
    title: "Luxury Lakeside Estate",
    description: "Exclusive estate with lake access, gardens, and luxurious interiors.",
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811",
    price: 4900,
    location: "Lake George",
    country: "United States",
  },
  {
    title: "Forest Family Cabin",
    description: "Large family cabin surrounded by beautiful trees and hiking trails.",
    image: "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8",
    price: 1750,
    location: "Olympic Peninsula",
    country: "United States",
  },
  {
    title: "Downtown Modern Condo",
    description: "Modern condominium located close to shopping and city attractions.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    price: 1900,
    location: "Seattle",
    country: "United States",
  },
  {
    title: "Peaceful Ocean Retreat",
    description: "Relax in this quiet retreat with beautiful views of the ocean.",
    image: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2",
    price: 2350,
    location: "Santa Barbara",
    country: "United States",
  },
  {
    title: "Rustic Countryside Cottage",
    description: "A cozy countryside cottage perfect for a peaceful vacation.",
    image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef",
    price: 1350,
    location: "Nashville",
    country: "United States",
  },
  {
    title: "Luxury Sunset Villa",
    description: "Enjoy spectacular sunsets from this beautiful luxury villa.",
    image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d",
    price: 3700,
    location: "Palm Springs",
    country: "United States",
  },
  {
    title: "Cozy Downtown Loft",
    description: "Stylish loft apartment located in the heart of the city.",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
    price: 1400,
    location: "Chicago",
    country: "United States",
  },
  {
    title: "Private Island Villa",
    description: "Luxury island villa offering complete privacy and tropical views.",
    image: "https://images.unsplash.com/photo-1500534623283-312aade485b7",
    price: 5500,
    location: "Maui",
    country: "United States",
  },
  {
    title: "Mountain Lakeside Home",
    description: "Beautiful home combining peaceful lake views with mountain scenery.",
    image: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e",
    price: 2600,
    location: "Lake Tahoe",
    country: "United States",
  },
  {
    title: "Elegant Beach House",
    description: "Spacious beach house with modern interiors and ocean access.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
    price: 2800,
    location: "San Diego",
    country: "United States",
  },
  {
    title: "Modern Forest Home",
    description: "Contemporary home surrounded by peaceful forests and greenery.",
    image: "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8",
    price: 2200,
    location: "Portland",
    country: "United States",
  },
  {
    title: "Luxury City Villa",
    description: "Exclusive city villa with modern amenities and private outdoor space.",
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811",
    price: 3900,
    location: "Los Angeles",
    country: "United States",
  },
  {
    title: "Peaceful Garden Home",
    description: "Comfortable home surrounded by a beautiful private garden.",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6",
    price: 1500,
    location: "Sacramento",
    country: "United States",
  },
  {
    title: "Luxury Snow Chalet",
    description: "Premium chalet with cozy interiors and stunning snowy views.",
    image: "https://images.unsplash.com/photo-1542718610-a1d656d1884c",
    price: 3300,
    location: "Aspen",
    country: "United States",
  },
  {
    title: "Oceanfront Family Home",
    description: "Large family-friendly home located directly beside the ocean.",
    image: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2",
    price: 3100,
    location: "Honolulu",
    country: "United States",
  },
  {
    title: "Modern Hillside House",
    description: "Stylish hillside house offering beautiful city and mountain views.",
    image: "https://images.unsplash.com/photo-1600607688969-a5bfcd646154",
    price: 2750,
    location: "San Francisco",
    country: "United States",
  },
  {
    title: "Quiet Lake Cottage",
    description: "Peaceful cottage with direct access to a calm and beautiful lake.",
    image: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e",
    price: 1400,
    location: "Lake Placid",
    country: "United States",
  },
  {
    title: "Downtown Luxury Studio",
    description: "Modern luxury studio in the center of a vibrant downtown area.",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
    price: 1250,
    location: "New York City",
    country: "United States",
  },
  {
    title: "Private Coastal Retreat",
    description: "Secluded coastal retreat with beautiful views and peaceful surroundings.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    price: 2450,
    location: "Outer Banks",
    country: "United States",
  },
  {
    title: "Luxury Mountain Mansion",
    description: "Large luxury mansion surrounded by breathtaking mountain scenery.",
    image: "https://images.unsplash.com/photo-1510798831971-661eb04b3739",
    price: 5700,
    location: "Vail",
    country: "United States",
  },
  {
    title: "Cozy Riverside Home",
    description: "Comfortable home overlooking a beautiful river and green landscape.",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
    price: 1550,
    location: "Boise",
    country: "United States",
  },
  {
    title: "Tropical Ocean Villa",
    description: "Beautiful tropical villa with ocean views and private outdoor space.",
    image: "https://images.unsplash.com/photo-1500534623283-312aade485b7",
    price: 3800,
    location: "Key West",
    country: "United States",
  },
  {
    title: "Historic Luxury Home",
    description: "Historic home renovated with modern luxury and elegant interiors.",
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994",
    price: 2900,
    location: "Charleston",
    country: "United States",
  },
  {
    title: "Modern Lake Villa",
    description: "Modern villa overlooking a peaceful lake with beautiful outdoor areas.",
    image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d",
    price: 3400,
    location: "Orlando",
    country: "United States",
  },
  {
    title: "Forest View Lodge",
    description: "Spacious lodge offering beautiful forest views and peaceful surroundings.",
    image: "https://images.unsplash.com/photo-1510798831971-661eb04b3739",
    price: 1900,
    location: "Boulder",
    country: "United States",
  },
  {
    title: "Luxury Beach Retreat",
    description: "Premium retreat located directly on a beautiful sandy beach.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
    price: 3600,
    location: "Naples",
    country: "United States",
  },
  {
    title: "Affordable City Apartment",
    description: "Comfortable and affordable apartment close to public transportation.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    price: 850,
    location: "Philadelphia",
    country: "United States",
  },
  {
    title: "Luxury Countryside Estate",
    description: "Beautiful private estate surrounded by green fields and peaceful nature.",
    image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef",
    price: 4100,
    location: "Lexington",
    country: "United States",
  },
  {
    title: "Cozy Mountain Getaway",
    description: "A comfortable mountain getaway perfect for a relaxing vacation.",
    image: "https://images.unsplash.com/photo-1480074568708-e7b720bb3f09",
    price: 1600,
    location: "Flagstaff",
    country: "United States",
  },
  {
    title: "Modern Beachfront Condo",
    description: "Stylish beachfront condo with beautiful ocean views.",
    image: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2",
    price: 2250,
    location: "Fort Lauderdale",
    country: "United States",
  },
  {
    title: "Private Forest Cabin",
    description: "Secluded cabin surrounded by tall trees and peaceful nature.",
    image: "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8",
    price: 1300,
    location: "Montana",
    country: "United States",
  },
  {
    title: "Luxury Skyline Apartment",
    description: "High-end apartment with panoramic views of the city skyline.",
    image: "https://images.unsplash.com/photo-1515263487990-61b07816b324",
    price: 2500,
    location: "Atlanta",
    country: "United States",
  },
  {
    title: "Peaceful Coastal Cottage",
    description: "Charming cottage perfect for a quiet vacation near the sea.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    price: 1550,
    location: "Destin",
    country: "United States",
  },
  {
    title: "Modern Desert Villa",
    description: "Stylish villa surrounded by beautiful desert landscapes.",
    image: "https://images.unsplash.com/photo-1600607688969-a5bfcd646154",
    price: 2700,
    location: "Scottsdale",
    country: "United States",
  },
  {
    title: "Luxury Family Estate",
    description: "Spacious estate with premium amenities for a comfortable family stay.",
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811",
    price: 4600,
    location: "Dallas",
    country: "United States",
  },
  {
    title: "Charming Downtown Home",
    description: "Beautiful home located within walking distance of downtown attractions.",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be",
    price: 1350,
    location: "Austin",
    country: "United States",
  },
  {
    title: "Mountain Lake Retreat",
    description: "Peaceful retreat offering spectacular views of mountains and lakes.",
    image: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e",
    price: 2300,
    location: "Lake Tahoe",
    country: "United States",
  },
  {
    title: "Luxury Ocean Mansion",
    description: "Exclusive oceanfront mansion with luxurious rooms and private amenities.",
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811",
    price: 6200,
    location: "Malibu",
    country: "United States",
  },
  {
    title: "Cozy Urban Studio",
    description: "Small modern studio perfect for travelers exploring the city.",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
    price: 900,
    location: "Seattle",
    country: "United States",
  },
  {
    title: "Peaceful Mountain Home",
    description: "Comfortable mountain home surrounded by nature and fresh air.",
    image: "https://images.unsplash.com/photo-1510798831971-661eb04b3739",
    price: 1850,
    location: "Denver",
    country: "United States",
  },
  {
    title: "Elegant Waterfront House",
    description: "Beautiful waterfront house with modern interiors and peaceful views.",
    image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d",
    price: 3100,
    location: "Seattle",
    country: "United States",
  },
  {
    title: "Rustic Beach Cottage",
    description: "Simple and charming cottage located near a quiet beach.",
    image: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2",
    price: 1450,
    location: "Galveston",
    country: "United States",
  },
  {
    title: "Luxury Garden Villa",
    description: "Elegant villa surrounded by beautiful gardens and outdoor spaces.",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6",
    price: 2800,
    location: "San Jose",
    country: "United States",
  },
  {
    title: "Modern City Penthouse",
    description: "Spacious penthouse with luxurious interiors and incredible city views.",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c",
    price: 4500,
    location: "Chicago",
    country: "United States",
  },
  {
    title: "Cozy Winter Retreat",
    description: "Warm retreat surrounded by beautiful snowy landscapes.",
    image: "https://images.unsplash.com/photo-1542718610-a1d656d1884c",
    price: 1950,
    location: "Vermont",
    country: "United States",
  },
  {
    title: "Sunny Coastal Villa",
    description: "Bright villa with plenty of sunlight and beautiful coastal views.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
    price: 2650,
    location: "Santa Barbara",
    country: "United States",
  },
];

module.exports = { data: sampleListings };